"""change default

Revision ID: 255f9d342c1b
Revises: 283ef21789f4
Create Date: 2025-12-23 10:25:16.272476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255f9d342c1b'
down_revision = '283ef21789f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IP', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('fk_vm_request_vm_id', ['vmid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('IP')

    # ### end Alembic commands ###
