"""Add vmid to VMRequest

Revision ID: c6a4f2d1b7a2
Revises: bdc49e99d57f
Create Date: 2025-12-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a4f2d1b7a2'
down_revision = 'bdc49e99d57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm_request', sa.Column('vmid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm_request', 'vmid')
    # ### end Alembic commands ###
