"""Add vm_category to VMRequest

Revision ID: e3d4f5a6b7c8
Revises: c6a4f2d1b7a2
Create Date: 2025-12-14 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d4f5a6b7c8'
down_revision = 'c6a4f2d1b7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm_request', sa.Column('vm_category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm_request', 'vm_category')
    # ### end Alembic commands ###
