"""Remove vm_category from VMRequest

Revision ID: f2a3b4c5d6e7
Revises: e3d4f5a6b7c8
Create Date: 2025-12-22 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a3b4c5d6e7'
down_revision = 'e3d4f5a6b7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm_request', 'vm_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm_request', sa.Column('vm_category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###